-- ============================================================
-- DTMS MySQL Schema
-- Dijalankan otomatis saat server start (idempotent)
-- ============================================================

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  `role` VARCHAR(100) DEFAULT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `company` VARCHAR(255) DEFAULT NULL,
  `supplierId` VARCHAR(50) DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_username` (`username`),
  UNIQUE KEY `uq_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `toolings` (
  `id` VARCHAR(50) NOT NULL,
  `name` VARCHAR(255) DEFAULT NULL,
  `type` VARCHAR(100) DEFAULT NULL,
  `partNumber` VARCHAR(100) DEFAULT NULL,
  `partName` VARCHAR(255) DEFAULT NULL,
  `model` VARCHAR(100) DEFAULT NULL,
  `supplier` VARCHAR(255) DEFAULT NULL,
  `supplierId` VARCHAR(50) DEFAULT NULL,
  `supplierAddress` VARCHAR(500) DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  `condition` VARCHAR(50) DEFAULT NULL,
  `owner` VARCHAR(100) DEFAULT NULL,
  `lifetime` VARCHAR(100) DEFAULT NULL,
  `maxShoot` INT DEFAULT NULL,
  `lastMaintenance` VARCHAR(50) DEFAULT NULL,
  `maker` VARCHAR(255) DEFAULT NULL,
  `weight` VARCHAR(50) DEFAULT NULL,
  `tonnage` VARCHAR(50) DEFAULT NULL,
  `dimensions` VARCHAR(100) DEFAULT NULL,
  `toolImage` VARCHAR(1000) DEFAULT NULL,
  `toolImage2` VARCHAR(1000) DEFAULT NULL,
  `partImage` VARCHAR(1000) DEFAULT NULL,
  `material` VARCHAR(100) DEFAULT NULL,
  `depreciationType` VARCHAR(50) DEFAULT NULL,
  `depreciationValue` VARCHAR(50) DEFAULT NULL,
  `qtyDepreciation` VARCHAR(50) DEFAULT NULL,
  `paNumber` VARCHAR(100) DEFAULT NULL,
  `paDocumentName` VARCHAR(255) DEFAULT NULL,
  `paDocumentPath` VARCHAR(500) DEFAULT NULL,
  `drawingDiesName` VARCHAR(255) DEFAULT NULL,
  `drawingDiesPath` VARCHAR(500) DEFAULT NULL,
  `price` VARCHAR(100) DEFAULT NULL,
  `notes` TEXT,
  `pic` VARCHAR(255) DEFAULT NULL,
  `picEmail` VARCHAR(255) DEFAULT NULL,
  `picPhone` VARCHAR(100) DEFAULT NULL,
  `qtyPerTooling` VARCHAR(50) DEFAULT NULL,
  `mapUrl` TEXT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `maintenanceLogs` (
  `id` VARCHAR(50) NOT NULL,
  `toolId` VARCHAR(50) DEFAULT NULL,
  `toolName` VARCHAR(255) DEFAULT NULL,
  `dateStart` VARCHAR(50) DEFAULT NULL,
  `dateEnd` VARCHAR(50) DEFAULT NULL,
  `type` VARCHAR(100) DEFAULT NULL,
  `description` TEXT,
  `status` VARCHAR(50) DEFAULT NULL,
  `evidence` VARCHAR(255) DEFAULT NULL,
  `evidencePath` VARCHAR(500) DEFAULT NULL,
  `requestedBy` VARCHAR(255) DEFAULT NULL,
  `cost` VARCHAR(100) DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `supplierTasks` (
  `id` VARCHAR(50) NOT NULL,
  `toolId` VARCHAR(50) DEFAULT NULL,
  `toolName` VARCHAR(255) DEFAULT NULL,
  `supplier` VARCHAR(255) DEFAULT NULL,
  `supplierId` VARCHAR(50) DEFAULT NULL,
  `type` VARCHAR(100) DEFAULT NULL,
  `description` TEXT,
  `assignedDate` VARCHAR(50) DEFAULT NULL,
  `dueDate` VARCHAR(50) DEFAULT NULL,
  `status` VARCHAR(50) DEFAULT NULL,
  `priority` VARCHAR(50) DEFAULT NULL,
  `completedDate` VARCHAR(50) DEFAULT NULL,
  `evidence` VARCHAR(255) DEFAULT NULL,
  `evidencePath` VARCHAR(500) DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `shootLogs` (
  `id` VARCHAR(50) NOT NULL,
  `toolId` VARCHAR(50) DEFAULT NULL,
  `month` VARCHAR(10) DEFAULT NULL,
  `inputDate` VARCHAR(50) DEFAULT NULL,
  `shootCount` INT DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `productionLogs` (
  `id` VARCHAR(50) NOT NULL,
  `toolId` VARCHAR(50) DEFAULT NULL,
  `shootLogId` VARCHAR(50) DEFAULT NULL,
  `actualPartOk` INT DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `deliveryLogs` (
  `id` VARCHAR(50) NOT NULL,
  `toolId` VARCHAR(50) DEFAULT NULL,
  `month` VARCHAR(10) DEFAULT NULL,
  `inputDate` VARCHAR(50) DEFAULT NULL,
  `qtyDelivered` INT DEFAULT NULL,
  `qtyOk` INT DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `movementLogs` (
  `id` VARCHAR(50) NOT NULL,
  `toolId` VARCHAR(50) DEFAULT NULL,
  `toolName` VARCHAR(255) DEFAULT NULL,
  `fromLocation` VARCHAR(255) DEFAULT NULL,
  `toLocation` VARCHAR(255) DEFAULT NULL,
  `date` VARCHAR(50) DEFAULT NULL,
  `reason` TEXT,
  `status` VARCHAR(50) DEFAULT NULL,
  `requestedBy` VARCHAR(255) DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT DEFAULT NULL,
  `message` TEXT,
  `time` VARCHAR(50) DEFAULT NULL,
  `read` TINYINT(1) NOT NULL DEFAULT 0,
  `type` VARCHAR(50) DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `auditLogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(50) DEFAULT NULL,
  `userId` INT DEFAULT NULL,
  `userName` VARCHAR(255) DEFAULT NULL,
  `action` TEXT,
  `icon` VARCHAR(50) DEFAULT NULL,
  `color` VARCHAR(20) DEFAULT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- KPI dihitung otomatis dari data riil (read-only)
DROP VIEW IF EXISTS `kpis`;
DROP TABLE IF EXISTS `kpis`;
CREATE VIEW `kpis` AS
  SELECT
    (SELECT COUNT(*) FROM `toolings` WHERE `status` = 'Aktif') AS `totalActive`,
    (SELECT COUNT(*) FROM `maintenanceLogs` WHERE `status` IN ('Menunggu Persetujuan', 'Sedang Berlangsung')) AS `openRepairs`,
    (SELECT COUNT(*) FROM `movementLogs` WHERE `status` = 'Menunggu Persetujuan') AS `pendingApprovals`,
    (SELECT COUNT(*) FROM `supplierTasks` WHERE `status` = 'Overdue') AS `overdueTasks`;
